endpoints for follow and unfollow
Lakshya021/cpsc455-project pull request #40
Opened 2022-07-03 03:40 UTC by Lakshya021

added the endpoints for follow and unfollow
haven't been able to test as of yet.

2022-07-04 11:05 UTC, danielcrookall commented on server/controllers/userControllers.ts
>                  res.status(403).json("you allready follow this user");
typo in "already"

2022-07-04 17:37 UTC, swongg requested changes

2022-07-04 17:37 UTC, swongg commented on server/router.ts
> +router.put("/api/users/:id/follow", followUser);
Just an FYI -- It's considered bad practice to use verbs (i.e. follow, register) for our RESTFUL apis and instead, we should be sticking with nouns. I noticed that we have this in a lot of our routes which is fine for the sake of this project :)

Source: https://docs.microsoft.com/en-us/azure/architecture/best-practices/api-design
 _When possible, resource URIs should be based on nouns (the resource) and not verbs (the operations on the resource)._

2022-07-04 17:37 UTC, swongg commented on server/controllers/userControllers.ts
> +                console.log("comes inside");
probably should remove the log statements unless you really need them. especially the "comes inside" one

2022-07-04 17:37 UTC, swongg commented on server/controllers/userControllers.ts
> +    if(req.params.id !== req.body.id){
👍

2022-07-04 17:37 UTC, swongg commented on server/router.ts
> +router.put("/api/users/:id/unfollow", unfollowUser);
Do we need both ```unfollow``` and ```follow``` endpoints or can they be combined into one?  Perhaps the ```PUT``` request can contain some type of indicator to specify of it's a _follow_ or an _unfollow_ ?

2022-07-13 20:33 UTC, Lakshya021 commented on server/controllers/userControllers.ts
> +      res.status(200).json(other);
Yeah, exactly what you said!

2022-07-13 23:48 UTC, Lakshya021 commented on server/router.ts
> +router.put("/api/users/:id/follow", followUser);
Good point Steven! I have modified it in the new commit.

2022-07-14 15:24 UTC, swongg commented on server/router.ts
> +// router.put("/api/users/:id", unfollowUser);
please remove this commented out cde

2022-07-14 15:36 UTC, swongg commented on server/controllers/userControllers.ts
> +export const editUser = (req:Request, res: Response) => {
I was thinking for ```editUser```, we shouldn't have to specify the action type.
If we did it this way, we would essentially have to keep adding new cases to our switch statement everytime we want to modify a different field.

2022-07-14 17:39 UTC, merged