User authentication
Lakshya021/cpsc455-project pull request #5
Opened 2022-06-02 01:01 UTC by danielcrookall

Simple login/signup with Material UI. Protection against unauthorized access of backend routes. 

Tested with postman.

2022-06-02 01:45 UTC, snow2650 approved these changes

2022-06-02 17:59 UTC, swongg requested changes
Thanks for putting this together!

I pulled the branch to play around with it and noticed a few bugs:

1) Signing up will create the account in the database but this console will log this:
![sign-up bug](https://user-images.githubusercontent.com/46267622/171696259-24d8ea27-77cb-4b30-b549-edc74977b7c6.png)

Seems like the code always goes into this ```if block``` in ```Signup.tsx```:
`  if (data.errors) {
            console.log('line 75')
            Object.values(data.errors).forEach((err) => {
                if (err !== "") {
                    alert(err)
                }
            })
            throw new Error(data.message)
        }`
which throws an error and it gets caught in line 47 of the ```handleSubmit``` function and ```navigate("/homepage")``` will never get called.


2) I'm unable to sign-in with the newly created account despite entering all the credentials correct (double-checked!)
![sign-in bug](https://user-images.githubusercontent.com/46267622/171696317-ccdcb17f-4b56-4722-ae5e-f698a94ba75e.png)


Let me know if you want me to help debug this.

2022-06-02 18:08 UTC, swongg commented
Did we want our backend to be typescript as well? Up to you guys. 🤔

2022-06-02 18:28 UTC, swongg commented on client/src/pages/Signup.tsx
> +        const data = await response.json()
if an error is thrown in the ```fetch``` call, would ```response``` stay as ```undefined``` and would ```response.json()``` still work?

2022-06-02 18:38 UTC, swongg commented on client/src/pages/Signup.tsx
> +        const username = data.get('username');
could we add typing to ```username``` and ```password```?

2022-06-02 18:42 UTC, swongg commented on server/middleware/auth.js
> +import jwt from "jsonwebtoken";
Super cool stuff.

2022-06-02 18:43 UTC, swongg commented on server/models/user.model.js
> +userSchema.methods.getSignedToken = function () {
What happens if the client make a call to the backend and their token has expired?

2022-06-03 04:12 UTC, danielcrookall commented on client/src/pages/Signup.tsx
> +        const data = await response.json()
This is a good point. As it currently stands, since tryLogin is being called in a try catch, if response is ever undefined (which it shouldn't be) then response.json will throw TypeError: Cannot read properties of undefined and it will be caught in the try catch where the call originated. 
![image](https://user-images.githubusercontent.com/83941101/171784630-ceb349cc-1c28-456f-a90c-193f428ce7e6.png)

2022-06-03 04:14 UTC, danielcrookall commented on client/src/pages/Signup.tsx
> +        const username = data.get('username');
TS infers the type because the type was declared in the trySignup function below
![image](https://user-images.githubusercontent.com/83941101/171784876-66f857f4-7119-4076-a5dd-0ecca621039d.png)

2022-06-03 04:19 UTC, danielcrookall commented on server/models/user.model.js
> +userSchema.methods.getSignedToken = function () {
The token is only verified in the protect middleware: 
![image](https://user-images.githubusercontent.com/83941101/171785115-f9c1d167-9954-48fe-b5f3-5e2b67de82b3.png)
If the token doesn't exist, or doesn't pass the jwt.verify then then http request will just return with a Not authorized to access this route. 

If accessing a protected route from the frontend, you would have to specify the token in the header of your fetch/HTTP request, which would subsequently be checked in the backend. The request would look something like this: 
![image](https://user-images.githubusercontent.com/83941101/171785321-dbcad840-02a0-4bca-9d90-af88bafe499a.png)

because upon successful signup/login, the JWT token is stored in local storage.

2022-06-05 20:42 UTC, swongg commented on client/src/pages/Signup.tsx
> +        const data = await response.json()
makes sense. 👍

2022-06-05 20:44 UTC, swongg approved these changes
💯

2022-06-05 20:47 UTC, swongg commented on server/models/user.model.js
> +userSchema.methods.getSignedToken = function () {
Just to clarify -- currently, if the JWT token expires, the user will need to go through the login flow again? 🤔 
If that's the case, maybe we can implement something down the line where they can get a new JWT token without having to sign in again. 

Anyway, LGTM feel free to merge!

2022-06-05 20:52 UTC, merged

2022-06-06 01:08 UTC, danielcrookall commented on server/models/user.model.js
> +userSchema.methods.getSignedToken = function () {
ya, I think that's how it works. I think you can refresh the token. As it currently stands, none of the backend routes are currently blocked, so no request will be blocked. I'm not 100% sure how the automatic sign out logic would work. 

I think it would be more related to the frontend: https://javascript.plainenglish.io/building-an-auto-logout-session-timeout-with-react-using-hooks-e7804ef973ec